Algoritmo "semnome"
Var
num:inteiro
Inicio
escreval(:"digite um numero de 1 a 5")
   leia(num)
se num=1 entao
    escreval("numero um")
    senao
   se num=2 entao
   escreval("numero dois")
    senao
     se num=3 entao
     escreval("numero tres")
     senao
     se num=4 entao
     escreval("numero quatro")
     senao
     escreval("numero cinco")
     fimse
     fimse
     fimse
fimse
   




Fimalgoritmo