Algoritmo "semnome"
Var
idade:inteiro
inicio
escreval("digite a sua idade: ")
leia(idade)
se ((idade>=18) e (idade<=65))entao
escreval("seu voto e obrigatorio")
   senao
      se idade>65 entao
      escreval("seu voto e opicional")
      senao
      escreval("seu voto e opicional ")
      fimse
      se(( idade>=16)e (idade<18)) entao
      escreval("vc ainda nao vota")
       fimse
     fimse
     fimse


 fimalgoritmo

